method: bayes
name: sweep
metric:
  goal: minimize
  name: best_score_val
parameters:
  learning_rate:
    max: 0.3
    min: 0.01
  depth:
    max: 10
    min: 6
  border_count:
    value: 128
  l2_leaf_reg:
    min: 1.0
    max: 6.0
